"""empty message

Revision ID: 0634c96c0f53
Revises: 6a82d7b0da06
Create Date: 2016-05-20 20:17:34.271874

"""

# revision identifiers, used by Alembic.
revision = '0634c96c0f53'
down_revision = '6a82d7b0da06'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_slot')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_slot', mysql.ENUM(u'09:12', u'12:15', u'15:18', u'18:21'), nullable=True))
    ### end Alembic commands ###
