"""empty message

Revision ID: 0a1eccb8230e
Revises: 4c666cd3bdb9
Create Date: 2016-05-27 10:20:54.727109

"""

# revision identifiers, used by Alembic.
revision = '0a1eccb8230e'
down_revision = '4c666cd3bdb9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_shipment_detail', sa.Column('cart_id', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'order_shipment_detail', ['shipment_id', 'cart_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_shipment_detail', type_='unique')
    op.drop_column('order_shipment_detail', 'cart_id')
    ### end Alembic commands ###
