"""empty message

Revision ID: 13f1af15843a
Revises: 7b46f9a4c96d
Create Date: 2016-05-19 12:00:07.125189

"""

# revision identifiers, used by Alembic.
revision = '13f1af15843a'
down_revision = '7b46f9a4c96d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('parent_order_id', sa.String(length=255), nullable=True))
    op.add_column('order', sa.Column('status_id', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('total_shipping', sa.Float(precision='10,2'), nullable=True))
    op.create_index(op.f('ix_order_parent_order_id'), 'order', ['parent_order_id'], unique=False)
    op.drop_constraint(u'order_ibfk_2', 'order', type_='foreignkey')
    op.create_foreign_key(None, 'order', 'status', ['status_id'], ['id'])
    op.drop_column('order', 'status_code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('status_code', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_foreign_key(u'order_ibfk_2', 'order', 'status', ['status_code'], ['status_code'])
    op.drop_index(op.f('ix_order_parent_order_id'), table_name='order')
    op.drop_column('order', 'total_shipping')
    op.drop_column('order', 'status_id')
    op.drop_column('order', 'parent_order_id')
    ### end Alembic commands ###
