"""empty message

Revision ID: 197aa09c0e29
Revises: 0a1eccb8230e
Create Date: 2016-05-27 13:38:39.035303

"""

# revision identifiers, used by Alembic.
revision = '197aa09c0e29'
down_revision = '0a1eccb8230e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_type')
    op.add_column('order_item', sa.Column('title', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'order_shipment_detail', ['shipment_id', 'cart_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_shipment_detail', type_='unique')
    op.drop_column('order_item', 'title')
    op.add_column('order', sa.Column('delivery_type', mysql.ENUM(u'NORMAL', u'SLOTTED'), nullable=False))
    ### end Alembic commands ###
