"""empty message

Revision ID: 1c1f460b722f
Revises: f201b9f814c6
Create Date: 2016-05-26 15:39:07.917783

"""

# revision identifiers, used by Alembic.
revision = '1c1f460b722f'
down_revision = 'f201b9f814c6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(length=255), nullable=False),
    sa.Column('cart_item_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('promo_codes', sa.String(length=255), nullable=True),
    sa.Column('offer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('display_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('item_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('transfer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('same_day_delivery', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_item_cart_item_id'), 'cart_item', ['cart_item_id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('display_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('offer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('shipping_charge', sa.Float(precision='10,2'), nullable=True),
    sa.Column('item_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('transfer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_item_id'), 'order_item', ['item_id'], unique=False)
    op.drop_table('order__item')
    op.drop_table('cart__item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart__item',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cart_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cart_item_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('promo_codes', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('offer_price', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('display_price', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('item_discount', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('transfer_price', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('same_day_delivery', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], [u'cart.cart_reference_uuid'], name=u'cart__item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.create_table('order__item',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('item_id', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('display_price', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('offer_price', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('shipping_charge', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('item_discount', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('transfer_price', mysql.FLOAT(precision=10, scale=2), nullable=True),
    sa.Column('order_id', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], [u'order.order_reference_id'], name=u'order__item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    op.drop_index(op.f('ix_order_item_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_cart_item_cart_item_id'), table_name='cart_item')
    op.drop_table('cart_item')
    ### end Alembic commands ###
