"""empty message

Revision ID: 2ebcfa0a82cc
Revises: 670d6efddd16
Create Date: 2016-05-10 13:14:25.554024

"""

# revision identifiers, used by Alembic.
revision = '2ebcfa0a82cc'
down_revision = '670d6efddd16'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'shipping_address_ref',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=255),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'shipping_address_ref',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=255),
               nullable=False)
    ### end Alembic commands ###
