"""empty message

Revision ID: 34fe9cfa2abd
Revises: c694253966a0
Create Date: 2016-05-02 20:07:28.543828

"""

# revision identifiers, used by Alembic.
revision = '34fe9cfa2abd'
down_revision = 'c694253966a0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_slot', sa.Enum('09:12', '12:15', '15:18', '18:21', name='delivery_time_slots'), nullable=True))
    op.add_column('payment', sa.Column('payment_mode', sa.Enum('COD', 'SODEXO', 'PREPAID', 'TICKET', name='payment_mode_type'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'payment_mode')
    op.drop_column('order', 'delivery_slot')
    ### end Alembic commands ###
