"""empty message

Revision ID: 4c666cd3bdb9
Revises: 3d2e810dc66b
Create Date: 2016-05-27 07:41:29.186955

"""

# revision identifiers, used by Alembic.
revision = '4c666cd3bdb9'
down_revision = '3d2e810dc66b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_shipment_detail', 'cart_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_shipment_detail', sa.Column('cart_id', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=False))
    ### end Alembic commands ###
