"""empty message

Revision ID: 5a966f1269e9
Revises: c7ee1cc9bbd5
Create Date: 2016-05-26 16:15:39.757352

"""

# revision identifiers, used by Alembic.
revision = '5a966f1269e9'
down_revision = 'c7ee1cc9bbd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_shipment_detail', ['shipment_id'])
    op.create_foreign_key(None, 'cart_item', 'order_shipment_detail', ['shipment_id'], ['shipment_id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_constraint(None, 'order_shipment_detail', type_='unique')
    ### end Alembic commands ###
