"""empty message

Revision ID: 670d6efddd16
Revises: 78a35c0f3d0b
Create Date: 2016-05-10 12:39:38.067759

"""

# revision identifiers, used by Alembic.
revision = '670d6efddd16'
down_revision = '78a35c0f3d0b'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('cart_geo_user_idx', 'cart', ['geo_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_cart__item_cart_item_id'), 'cart__item', ['cart_item_id'], unique=False)
    op.create_index('order_geo_user_idx', 'order', ['geo_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_order__item_item_id'), 'order__item', ['item_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order__item_item_id'), table_name='order__item')
    op.drop_index('order_geo_user_idx', table_name='order')
    op.drop_index(op.f('ix_cart__item_cart_item_id'), table_name='cart__item')
    op.drop_index('cart_geo_user_idx', table_name='cart')
    ### end Alembic commands ###
