"""empty message

Revision ID: 69a04e717ce3
Revises: 0634c96c0f53
Create Date: 2016-05-20 20:17:46.713801

"""

# revision identifiers, used by Alembic.
revision = '69a04e717ce3'
down_revision = '0634c96c0f53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('delivery_slot', sa.String(length=512), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_slot')
    ### end Alembic commands ###
