"""empty message

Revision ID: 6a82d7b0da06
Revises: 9707f81164c0
Create Date: 2016-05-20 19:21:02.296719

"""

# revision identifiers, used by Alembic.
revision = '6a82d7b0da06'
down_revision = '9707f81164c0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'delivery_due_date')
    op.drop_column('order__item', 'order_partial_discount')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order__item', sa.Column('order_partial_discount', mysql.FLOAT(precision=10, scale=2), nullable=True))
    op.add_column('order', sa.Column('delivery_due_date', sa.DATE(), nullable=True))
    ### end Alembic commands ###
