"""empty message

Revision ID: 6f55665da45d
Revises: 9a139dea1c44
Create Date: 2016-06-01 06:41:56.209784

"""

# revision identifiers, used by Alembic.
revision = '6f55665da45d'
down_revision = '9a139dea1c44'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_shipment_detail', 'cart', ['cart_id'], ['cart_reference_uuid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_shipment_detail', type_='foreignkey')
    ### end Alembic commands ###
