"""empty message

Revision ID: 78a35c0f3d0b
Revises: 1e6911078080
Create Date: 2016-05-10 10:47:27.748286

"""

# revision identifiers, used by Alembic.
revision = '78a35c0f3d0b'
down_revision = '1e6911078080'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('payment_mode', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'payment_mode')
    ### end Alembic commands ###
