"""empty message

Revision ID: 7a17684de9d0
Revises: 2fa2ab76429d
Create Date: 2016-05-09 09:41:55.738829

"""

# revision identifiers, used by Alembic.
revision = '7a17684de9d0'
down_revision = '2fa2ab76429d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'delivery_slot',
               existing_type=mysql.ENUM(u'09:12', u'12:15', u'15:18', u'18:21'),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'delivery_slot',
               existing_type=mysql.ENUM(u'09:12', u'12:15', u'15:18', u'18:21'),
               nullable=False)
    ### end Alembic commands ###
