"""empty message

Revision ID: 7b46f9a4c96d
Revises: 37b05985b6a7
Create Date: 2016-05-18 10:09:21.894720

"""

# revision identifiers, used by Alembic.
revision = '7b46f9a4c96d'
down_revision = '37b05985b6a7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=255), nullable=False),
    sa.Column('status_description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_code')
    )
    op.add_column(u'cart__item', sa.Column('transfer_price', sa.Float(precision='10,2'), nullable=True))
    op.drop_column(u'cart__item', 'transferPrice')
    op.add_column(u'order', sa.Column('status_code', sa.String(length=255), nullable=True))
    op.add_column(u'order', sa.Column('total_discount', sa.Float(precision='10,2'), nullable=True))
    op.add_column(u'order', sa.Column('total_display_price', sa.Float(precision='10,2'), nullable=True))
    op.add_column(u'order', sa.Column('total_offer_price', sa.Float(precision='10,2'), nullable=False))
    op.add_column(u'order', sa.Column('total_payble_amount', sa.Float(precision='10,2'), nullable=True))
    op.create_index('order_user_idx', 'order', ['user_id'], unique=False)
    op.drop_index('order_geo_user_idx', table_name='order')
    op.create_foreign_key(None, 'order', 'status', ['status_code'], ['status_code'])
    op.add_column(u'order__item', sa.Column('transfer_price', sa.Float(precision='10,2'), nullable=True))
    op.add_column(u'payment', sa.Column('paid_amount', sa.Float(precision='10,2'), nullable=True))
    op.drop_column(u'payment', 'payble_amount')
    op.drop_column(u'payment', 'total_offer_price')
    op.drop_column(u'payment', 'total_display_price')
    op.drop_column(u'payment', 'total_discount')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'payment', sa.Column('total_discount', mysql.FLOAT(precision=10, scale=2), nullable=True))
    op.add_column(u'payment', sa.Column('total_display_price', mysql.FLOAT(precision=10, scale=2), nullable=True))
    op.add_column(u'payment', sa.Column('total_offer_price', mysql.FLOAT(precision=10, scale=2), nullable=False))
    op.add_column(u'payment', sa.Column('payble_amount', mysql.FLOAT(precision=10, scale=2), nullable=True))
    op.drop_column(u'payment', 'paid_amount')
    op.drop_column(u'order__item', 'transfer_price')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.create_index('order_geo_user_idx', 'order', ['geo_id', 'user_id'], unique=False)
    op.drop_index('order_user_idx', table_name='order')
    op.drop_column(u'order', 'total_payble_amount')
    op.drop_column(u'order', 'total_offer_price')
    op.drop_column(u'order', 'total_display_price')
    op.drop_column(u'order', 'total_discount')
    op.drop_column(u'order', 'status_code')
    op.add_column(u'cart__item', sa.Column('transferPrice', mysql.FLOAT(precision=10, scale=2), nullable=True))
    op.drop_column(u'cart__item', 'transfer_price')
    op.drop_table('status')
    ### end Alembic commands ###
