"""empty message

Revision ID: 7b81e6857290
Revises: 2378dea04d8a
Create Date: 2016-05-04 13:50:00.504317

"""

# revision identifiers, used by Alembic.
revision = '7b81e6857290'
down_revision = '2378dea04d8a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart__item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(length=255), nullable=True),
    sa.Column('cart_item_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('promo_codes', sa.String(length=255), nullable=True),
    sa.Column('offer_price', sa.Numeric(), nullable=True),
    sa.Column('display_price', sa.Numeric(), nullable=True),
    sa.Column('item_discount', sa.Numeric(), nullable=True),
    sa.Column('order_partial_discount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_reference_uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cart_item')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_item',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('cart_id', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True),
    sa.Column('cart_item_id', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('promo_codes', mysql.VARCHAR(collation=u'utf8_bin', length=255), nullable=True),
    sa.Column('offer_price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('display_price', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('item_discount', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('order_partial_discount', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], [u'cart.cart_reference_uuid'], name=u'cart_item_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('cart__item')
    ### end Alembic commands ###
