"""empty message

Revision ID: 9a139dea1c44
Revises: 197aa09c0e29
Create Date: 2016-05-30 15:55:44.700094

"""

# revision identifiers, used by Alembic.
revision = '9a139dea1c44'
down_revision = '197aa09c0e29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'cart_item', 'order_shipment_detail', ['shipment_id'], ['shipment_id'])
    op.add_column('order_item', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_index('shipment_id_2', table_name='order_shipment_detail')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('shipment_id_2', 'order_shipment_detail', ['shipment_id', 'cart_id'], unique=True)
    op.drop_column('order_item', 'image_url')
    op.drop_constraint(None, 'cart_item', type_='foreignkey')
    op.drop_column('cart_item', 'image_url')
    ### end Alembic commands ###
