"""empty message

Revision ID: ac205f757bdc
Revises: 7b81e6857290
Create Date: 2016-05-05 10:45:36.579485

"""

# revision identifiers, used by Alembic.
revision = 'ac205f757bdc'
down_revision = '7b81e6857290'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart__item', 'cart_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=255),
               nullable=False)
    op.alter_column('order__item', 'order_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=255),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order__item', 'order_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=255),
               nullable=True)
    op.alter_column('cart__item', 'cart_id',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=255),
               nullable=True)
    ### end Alembic commands ###
