"""empty message

Revision ID: b028dcc0cab3
Revises: f70d4279aa47
Create Date: 2016-06-29 10:05:41.344213

"""

# revision identifiers, used by Alembic.
revision = 'b028dcc0cab3'
down_revision = 'f70d4279aa47'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('pass_txn_id', sa.String(length=32), nullable=True))
    op.add_column('payment', sa.Column('total_amt', sa.Float(precision='10,2'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'total_amt')
    op.drop_column('payment', 'pass_txn_id')
    ### end Alembic commands ###
