"""empty message

Revision ID: bad470bf1571
Revises: d3050d1f4c40
Create Date: 2016-06-02 14:51:37.068419

"""

# revision identifiers, used by Alembic.
revision = 'bad470bf1571'
down_revision = 'd3050d1f4c40'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('total_cashback', sa.Float(precision='10,2'), nullable=True))
    op.add_column('cart_item', sa.Column('item_cashback', sa.Float(precision='10,2'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_item', 'item_cashback')
    op.drop_column('cart', 'total_cashback')
    ### end Alembic commands ###
