"""empty message

Revision ID: c30bb4f1f82c
Revises: bad470bf1571
Create Date: 2016-06-02 15:41:04.023978

"""

# revision identifiers, used by Alembic.
revision = 'c30bb4f1f82c'
down_revision = 'bad470bf1571'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('total_cashback', sa.Float(precision='10,2'), nullable=True))
    op.add_column('order_item', sa.Column('item_cashback', sa.Float(precision='10,2'), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'item_cashback')
    op.drop_column('order', 'total_cashback')
    ### end Alembic commands ###
