"""empty message

Revision ID: c3a46a5f94d0
Revises: b028dcc0cab3
Create Date: 2016-07-18 11:42:41.921079

"""

# revision identifiers, used by Alembic.
revision = 'c3a46a5f94d0'
down_revision = 'b028dcc0cab3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('address', 'pincode',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=32),
               nullable=False)
    op.create_index('cart_geo_user_idx', 'cart', ['geo_id', 'user_id'], unique=False)
    op.add_column('cart_item', sa.Column('seller_id', sa.String(length=255), nullable=True))
    op.create_index('order_user_idx', 'order', ['user_id'], unique=False)
    op.add_column('order_item', sa.Column('seller_id', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'seller_id')
    op.drop_index('order_user_idx', table_name='order')
    op.drop_column('cart_item', 'seller_id')
    op.drop_index('cart_geo_user_idx', table_name='cart')
    op.alter_column('address', 'pincode',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=32),
               nullable=True)
    ### end Alembic commands ###
