"""empty message

Revision ID: c7ee1cc9bbd5
Revises: 6722ba460a4a
Create Date: 2016-05-26 16:01:15.933554

"""

# revision identifiers, used by Alembic.
revision = 'c7ee1cc9bbd5'
down_revision = '6722ba460a4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_shipment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=255), nullable=False),
    sa.Column('cart_id', sa.String(length=255), nullable=False),
    sa.Column('delivery_slot', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_shipment_detail_cart_id'), 'order_shipment_detail', ['cart_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_shipment_detail_cart_id'), table_name='order_shipment_detail')
    op.drop_table('order_shipment_detail')
    ### end Alembic commands ###
