"""empty message

Revision ID: f201b9f814c6
Revises: dbccde0d7aad
Create Date: 2016-05-25 22:03:34.545128

"""

# revision identifiers, used by Alembic.
revision = 'f201b9f814c6'
down_revision = 'dbccde0d7aad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart__item', sa.Column('title', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart__item', 'title')
    ### end Alembic commands ###
