"""empty message

Revision ID: f70d4279aa47
Revises: None
Create Date: 2016-06-24 01:28:06.172003

"""

# revision identifiers, used by Alembic.
revision = 'f70d4279aa47'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_code', sa.String(length=32), nullable=False),
    sa.Column('status_description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_code')
    )
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('pincode', sa.String(length=32), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('landmark', sa.String(length=512), nullable=True),
    sa.Column('address_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address_hash')
    )
    op.create_table('master_order',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('geo_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('order_source', sa.String(length=32), nullable=True),
    sa.Column('order_type', sa.String(length=32), nullable=True),
    sa.Column('promo_codes', sa.String(length=255), nullable=True),
    sa.Column('promo_types', sa.String(length=255), nullable=True),
    sa.Column('promo_max_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('payment_mode', sa.String(length=32), nullable=True),
    sa.Column('total_offer_price', sa.Float(precision='10,2'), nullable=False),
    sa.Column('total_display_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_cashback', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_shipping', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_payble_amount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('shipping_address_ref', sa.String(length=128), nullable=False),
    sa.Column('billing_address_ref', sa.String(length=128), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.String(length=32), nullable=True),
    sa.Column('ops_panel_status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shipping_address_ref'], ['address.address_hash'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_master_order_order_id'), 'master_order', ['order_id'], unique=False)
    op.create_table('cart',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_reference_uuid', sa.String(length=255), nullable=False),
    sa.Column('geo_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=True),
    sa.Column('order_source_reference', sa.String(length=32), nullable=True),
    sa.Column('promo_codes', sa.String(length=255), nullable=True),
    sa.Column('selected_freebee_items', sa.String(length=255), nullable=True),
    sa.Column('total_offer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_cashback', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_display_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_shipping_charges', sa.Float(precision='10,2'), nullable=True),
    sa.Column('shipping_address_ref', sa.String(length=128), nullable=True),
    sa.Column('payment_mode', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['shipping_address_ref'], ['address.address_hash'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_reference_uuid')
    )
    op.create_table('order',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_order_id', sa.String(length=64), nullable=False),
    sa.Column('order_reference_id', sa.String(length=64), nullable=False),
    sa.Column('geo_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=True),
    sa.Column('order_source_reference', sa.String(length=32), nullable=True),
    sa.Column('promo_codes', sa.String(length=255), nullable=True),
    sa.Column('promo_types', sa.String(length=255), nullable=True),
    sa.Column('promo_max_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('shipping_address_ref', sa.String(length=128), nullable=False),
    sa.Column('billing_address_ref', sa.String(length=128), nullable=True),
    sa.Column('delivery_type', sa.Integer(), nullable=True),
    sa.Column('delivery_slot', sa.String(length=512), nullable=True),
    sa.Column('freebie', sa.String(length=255), nullable=True),
    sa.Column('total_offer_price', sa.Float(precision='10,2'), nullable=False),
    sa.Column('total_display_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_cashback', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_shipping', sa.Float(precision='10,2'), nullable=True),
    sa.Column('total_payble_amount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_order_id'], ['master_order.order_id'], ),
    sa.ForeignKeyConstraint(['shipping_address_ref'], ['address.address_hash'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_reference_id')
    )
    op.create_index(op.f('ix_order_parent_order_id'), 'order', ['parent_order_id'], unique=False)
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('payment_gateway', sa.String(length=32), nullable=True),
    sa.Column('pg_txn_id', sa.String(length=32), nullable=True),
    sa.Column('bank_txn_id', sa.String(length=128), nullable=True),
    sa.Column('txn_date', sa.DateTime(), nullable=True),
    sa.Column('txn_amt', sa.Float(precision='10,2'), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['master_order.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_shipment_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.String(length=32), nullable=False),
    sa.Column('cart_id', sa.String(length=255), nullable=False),
    sa.Column('delivery_type', sa.Integer(), nullable=True),
    sa.Column('delivery_slot', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_reference_uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('display_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('offer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('shipping_charge', sa.Float(precision='10,2'), nullable=True),
    sa.Column('item_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('item_cashback', sa.Float(precision='10,2'), nullable=True),
    sa.Column('transfer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_reference_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_item_id'), 'order_item', ['item_id'], unique=False)
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.String(length=255), nullable=False),
    sa.Column('cart_item_id', sa.String(length=128), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('promo_codes', sa.String(length=255), nullable=True),
    sa.Column('offer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('display_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('item_discount', sa.Float(precision='10,2'), nullable=True),
    sa.Column('item_cashback', sa.Float(precision='10,2'), nullable=True),
    sa.Column('transfer_price', sa.Float(precision='10,2'), nullable=True),
    sa.Column('same_day_delivery', sa.String(length=16), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('shipment_id', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.cart_reference_uuid'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['order_shipment_detail.shipment_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cart_item_cart_item_id'), 'cart_item', ['cart_item_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cart_item_cart_item_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_order_item_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_table('order_shipment_detail')
    op.drop_table('payment')
    op.drop_index(op.f('ix_order_parent_order_id'), table_name='order')
    op.drop_table('order')
    op.drop_table('cart')
    op.drop_index(op.f('ix_master_order_order_id'), table_name='master_order')
    op.drop_table('master_order')
    op.drop_table('address')
    op.drop_table('status')
    ### end Alembic commands ###
